/***************************************************************************
 *   Copyright (C) 2013 by James Holodnak                                  *
 *   jamesholodnak@gmail.com                                               *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 ***************************************************************************/

#include <string.h>
#include "mapperinc.h"

struct unif_board_s {
	const char *name;
	int boardid;
};

#define UNIF_BOARD_START()		static struct unif_board_s boards[] = {
#define UNIF_BOARD_END()		{0,-1}};
#define UNIF_BOARD(s,b)			{s,b},

UNIF_BOARD_START()

	//licensed
	//NROM boards
	UNIF_BOARD("NES-NROM",						B_NINTENDO_NROM)
	UNIF_BOARD("NES-NROM-128",					B_NINTENDO_NROM)
	UNIF_BOARD("NES-NROM-256",					B_NINTENDO_NROM)
	UNIF_BOARD("HVC-NROM-128",					B_NINTENDO_NROM)
	UNIF_BOARD("HVC-NROM-256",					B_NINTENDO_NROM)
	UNIF_BOARD("IREM-NROM-128",				B_NINTENDO_NROM)
	UNIF_BOARD("IREM-NROM-256",				B_NINTENDO_NROM)
	UNIF_BOARD("TAITO-NROM-128",				B_NINTENDO_NROM)
	UNIF_BOARD("TAITO-NROM-256",				B_NINTENDO_NROM)
	UNIF_BOARD("KONAMI-NROM-128",				B_NINTENDO_NROM)
	UNIF_BOARD("KONAMI-NROM-256",				B_NINTENDO_NROM)
	UNIF_BOARD("JALECO-JF-01",					B_NINTENDO_NROM)
	UNIF_BOARD("JALECO-JF-02",					B_NINTENDO_NROM)
	UNIF_BOARD("JALECO-JF-03",					B_NINTENDO_NROM)
	UNIF_BOARD("JALECO-JF-04",					B_NINTENDO_NROM)
	UNIF_BOARD("TENGEN-800003",				B_NINTENDO_NROM)

	//RROM boards
	UNIF_BOARD("NES-RROM",						B_NINTENDO_NROM)
	UNIF_BOARD("NES-RROM-128",					B_NINTENDO_NROM)
	UNIF_BOARD("HVC-RROM",						B_NINTENDO_NROM)

	//SxROM boards
	UNIF_BOARD("NES-SAROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SBROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SCROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SEROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SFROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SGROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SHROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SJROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SKROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SLROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SNROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SOROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SUROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("NES-SXROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SAROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SBROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SCROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SEROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SFROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SGROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SHROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SJROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SKROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SLROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SNROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SOROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SUROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("HVC-SXROM",						B_NINTENDO_SxROM)
	UNIF_BOARD("KONAMI-SLROM",					B_NINTENDO_SxROM)

	//UxROM boards
	UNIF_BOARD("NES-UNROM",						B_NINTENDO_UxROM)
	UNIF_BOARD("HVC-UNROM",						B_NINTENDO_UxROM)
	UNIF_BOARD("IREM-UNROM",					B_NINTENDO_UxROM)
	UNIF_BOARD("KONAMI-UNROM",					B_NINTENDO_UxROM)
	UNIF_BOARD("NES-UOROM",						B_NINTENDO_UxROM)
	UNIF_BOARD("HVC-UOROM",						B_NINTENDO_UxROM)
	UNIF_BOARD("JALECO-JF-15",					B_NINTENDO_UxROM)
	UNIF_BOARD("JALECO-JF-18",					B_NINTENDO_UxROM)
	UNIF_BOARD("JALECO-JF-39",					B_NINTENDO_UxROM)					//verify this

	//TxROM boards
	UNIF_BOARD("NES-TSROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("NES-TLROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("NES-TKROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("NES-TFROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("NES-TBROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("NES-TVROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("NES-TKEPROM",					B_NINTENDO_TxROM)
	UNIF_BOARD("HVC-TLROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("HVC-TKROM",						B_NINTENDO_TxROM)
	UNIF_BOARD("KONAMI-TLROM",					B_NINTENDO_TxROM)

	//TxROM boards
	UNIF_BOARD("NES-HKROM",						B_NINTENDO_HxROM)

	//TQROM
	UNIF_BOARD("NES-TQROM",						B_NINTENDO_TQROM)

	//UN1ROM
	UNIF_BOARD("HVC-UN1ROM",					B_NINTENDO_UN1ROM)

	//CxROM boards
	UNIF_BOARD("NES-CNROM",						B_NINTENDO_CNROM)
	UNIF_BOARD("KONAMI-74*139/74",			B_NINTENDO_CNROM)					//appears to be CNROM
	UNIF_BOARD("NES-CPROM",						B_NINTENDO_CPROM)

	//PxROM boards
	UNIF_BOARD("NES-PNROM",						B_NINTENDO_PxROM)
	UNIF_BOARD("NES-PEEOROM",					B_NINTENDO_PxROM)
	UNIF_BOARD("HVC-PEEOROM",					B_NINTENDO_PxROM)

	//FxROM boards
	UNIF_BOARD("NES-FJROM",						B_NINTENDO_FxROM)
	UNIF_BOARD("NES-FKROM",						B_NINTENDO_FxROM)

	//ExROM boards
	UNIF_BOARD("NES-EKROM",						B_NINTENDO_ExROM)
	UNIF_BOARD("NES-ELROM",						B_NINTENDO_ExROM)
	UNIF_BOARD("NES-ETROM",						B_NINTENDO_ExROM)
	UNIF_BOARD("NES-EWROM",						B_NINTENDO_ExROM)

	//DxROM boards
	UNIF_BOARD("NES-DEROM",						B_NINTENDO_DxROM)
	UNIF_BOARD("NES-DE1ROM",					B_NINTENDO_DxROM)
	UNIF_BOARD("NES-DRROM",						B_NINTENDO_DxROM)

	//EVENT board
	UNIF_BOARD("NES-EVENT",						B_NINTENDO_EVENT)

	//irem
	UNIF_BOARD("IREM-TAM-S1",					B_IREM_TAM_S1)
	UNIF_BOARD("IREM-H3001",					B_IREM_H3001)

	//taito
	UNIF_BOARD("TAITO-X1-005",					B_TAITO_X1_005)
	UNIF_BOARD("TAITO-X1-017",					B_TAITO_X1_017)

	//jaleco
	UNIF_BOARD("JALECO-JF-11",					B_JALECO_JF11)
	UNIF_BOARD("JALECO-JF-23",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-24",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-25",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-27",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-29",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-30",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-31",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-32",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-33",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-34",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-35",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-36",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-37",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-38",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-40",					B_JALECO_SS88006)
	UNIF_BOARD("JALECO-JF-41",					B_JALECO_SS88006)

	//konami vrc boards
	UNIF_BOARD("KONAMI-VRC-1",					B_KONAMI_VRC1)
	UNIF_BOARD("KONAMI-VRC-2",					B_KONAMI_VRC2)
	UNIF_BOARD("KONAMI-VRC-2A",				B_KONAMI_VRC2A)
	UNIF_BOARD("KONAMI-VRC-2B",				B_KONAMI_VRC2B)
	UNIF_BOARD("KONAMI-VRC-3",					B_KONAMI_VRC3)
	UNIF_BOARD("KONAMI-VRC-4",					B_KONAMI_VRC4B)
	UNIF_BOARD("KONAMI-VRC-4A",				B_KONAMI_VRC4A)
	UNIF_BOARD("KONAMI-VRC-4B",				B_KONAMI_VRC4B)
	UNIF_BOARD("KONAMI-VRC-4C",				B_KONAMI_VRC4C)
	UNIF_BOARD("KONAMI-VRC-4D",				B_KONAMI_VRC4D)
	UNIF_BOARD("KONAMI-VRC-4E",				B_KONAMI_VRC4E)
	UNIF_BOARD("KONAMI-VRC-6",					B_KONAMI_VRC6B)
	UNIF_BOARD("KONAMI-VRC-6A",				B_KONAMI_VRC6A)
	UNIF_BOARD("KONAMI-VRC-6B",				B_KONAMI_VRC6B)
	UNIF_BOARD("KONAMI-VRC-7",					B_KONAMI_VRC7B)
	UNIF_BOARD("KONAMI-VRC-7A",				B_KONAMI_VRC7A)
	UNIF_BOARD("KONAMI-VRC-7B",				B_KONAMI_VRC7B)

	//namcot
	UNIF_BOARD("NAMCOT-3433",					B_NAMCOT_34x3)
	UNIF_BOARD("NAMCOT-3443",					B_NAMCOT_34x3)
	UNIF_BOARD("NAMCOT-3453",					B_NAMCOT_3453)
	UNIF_BOARD("NAMCOT-3425",					B_NAMCOT_3425)

	//sunsoft
	UNIF_BOARD("SUNSOFT-1",						B_SUNSOFT_1)
	UNIF_BOARD("SUNSOFT-2",						B_SUNSOFT_2)
	UNIF_BOARD("SUNSOFT-3",						B_SUNSOFT_3)
	UNIF_BOARD("SUNSOFT-4",						B_SUNSOFT_4)
	UNIF_BOARD("SUNSOFT-5A",					B_SUNSOFT_5B)
	UNIF_BOARD("SUNSOFT-5B",					B_SUNSOFT_5B)

	//unlicensed
	//camerica
	UNIF_BOARD("CAMERICA-BF9093",				B_CAMERICA_BF9093)
	UNIF_BOARD("CAMERICA-ALGN",				B_CAMERICA_BF9093)
	UNIF_BOARD("CODEMASTERS-NR8N",			B_CAMERICA_BF9093)
	UNIF_BOARD("CAMERICA-BF9096",				B_CAMERICA_BF9096)
	UNIF_BOARD("CAMERICA-BF9097",				B_CAMERICA_BF9097)

	//tengen
	UNIF_BOARD("TENGEN-800002",				B_TENGEN_MIMIC_1)
	UNIF_BOARD("TENGEN-800004",				B_TENGEN_MIMIC_1)
	UNIF_BOARD("TENGEN-800030",				B_TENGEN_MIMIC_1)
	UNIF_BOARD("TENGEN-800032",				B_TENGEN_RAMBO_1)
	UNIF_BOARD("TENGEN-800037",				B_TENGEN_RAMBO_1)

	//txc
	UNIF_BOARD("UNL-22211",						B_TXC_22211A)
	UNIF_BOARD("UNL-22211-A",					B_TXC_22211A)
	UNIF_BOARD("UNL-22211-B",					B_TXC_22211B)
	UNIF_BOARD("UNL-22211-C",					B_TXC_22211C)

	//sachen
	UNIF_BOARD("UNL-SACHEN-74LS374N",		B_SACHEN_74LS374N)
	UNIF_BOARD("UNL-SACHEN-8259",				B_SACHEN_8259A)
	UNIF_BOARD("UNL-SACHEN-8259A",			B_SACHEN_8259A)
	UNIF_BOARD("UNL-SACHEN-8259B",			B_SACHEN_8259B)
	UNIF_BOARD("UNL-SACHEN-8259C",			B_SACHEN_8259C)
	UNIF_BOARD("UNL-SACHEN-8259D",			B_SACHEN_8259D)
	UNIF_BOARD("UNL-SA-72007",					B_SA_72007)
	UNIF_BOARD("UNL-SA-72008",					B_SA_72008)
	UNIF_BOARD("UNL-SA-0036",					B_SA_0036)
	UNIF_BOARD("UNL-SA-0037",					B_SA_0037)
	UNIF_BOARD("UNL-SA-016-1M",				B_SA_0161M)

	//other (unknown)
	UNIF_BOARD("BMC-70IN1",						B_BMC_70IN1)
	UNIF_BOARD("BMC-70IN1B",					B_BMC_70IN1B)
	UNIF_BOARD("BMC-SUPER700IN1",				B_BMC_SUPER700IN1)
	UNIF_BOARD("BMC-SUPER42IN1",				B_BMC_76IN1)
	UNIF_BOARD("BMC-FK23C",						B_BMC_FK23C)
	UNIF_BOARD("BMC-260IN1",					B_BMC_GOLDENGAME260IN1)

	UNIF_BOARD("BTL-MARIO1-MALEE2",			B_BTL_MARIO1_MALEE2)
	UNIF_BOARD("BTL-BIOMIRACLEA",				B_BTL_BIOMIRACLEA)
	UNIF_BOARD("MLT-CALTRON6IN1",				B_NTDEC_CALTRON6IN1)
	UNIF_BOARD("UNL-RACERMATE",				B_UNL_RACERMATE)
	UNIF_BOARD("UNL-H2288",						B_UNL_H2288)
	UNIF_BOARD("UNL-KASING",					B_KASING)
	UNIF_BOARD("UNL-SUPERLIONKING",			B_UNL_SUPERLIONKING)

	//ave
	UNIF_BOARD("AVE-NINA-01",					B_AVE_NINA_001)
	UNIF_BOARD("AVE-NINA-03",					B_AVE_NINA_006)
	UNIF_BOARD("AVE-NINA-06",					B_AVE_NINA_006)

	//homebrew
	UNIF_BOARD("UNL-DRIPGAME",					B_DRIPGAME)

	//unofficial, need verification or real board name
	UNIF_BOARD("BMC-65IN1",						B_BMC_65IN1)

UNIF_BOARD_END()

int mapper_get_mapperid_unif(char *str)
{
	int i;

	for(i=0;boards[i].boardid != -1;i++) {
		if(stricmp(str,boards[i].name) == 0)
			return(boards[i].boardid);
	}
	return(B_UNSUPPORTED);
}

const char *mapper_get_unif_boardname(int idx)
{
	if(boards[idx].boardid == -1 || boards[idx].name == 0)
		return(0);
	return(boards[idx].name);
}
