//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by nesemu2.rc
//
#define IDC_MYICON                      2
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDC_MAIN                        109
#define IDR_MAINFRAME                   128
#define IDD_DIALOG1                     129
#define IDD_DEBUGGER                    129
#define IDI_ICON1                       130
#define IDI_MAIN                        130
#define IDD_ABOUT                       131
#define IDD_MAPPERS                     132
#define IDD_CONFIG_GENERAL1             133
#define IDD_CONFIG_GENERAL              133
#define IDD_CONFIG_GENERAL2             134
#define IDD_CONFIG_PATHS                134
#define IDD_CONSOLE                     135
#define IDD_CONFIG_GENERAL3             136
#define IDD_CONFIG_NES                  136
#define IDD_BREAKPOINT                  137
#define IDR_ACCELERATOR                 138
#define IDD_CONFIG_GENERAL4             138
#define IDD_CONFIG_SYSTEM               138
#define IDD_CHEATSEARCH                 139
#define IDD_CARTDBFILES                 140
#define IDR_FILELISTMENU                141
#define IDD_FILEEDIT                    142
#define IDD_OPENEXT                     143
#define IDD_CONFIG_GENERAL5             144
#define IDD_CONFIG_PALETTE              144
#define IDC_EDIT1                       1000
#define IDC_AEDIT                       1000
#define IDC_DATAPATHEDIT                1000
#define IDC_CONSOLEEDIT                 1000
#define IDC_FDSBIOSEDIT                 1000
#define IDC_XEDIT                       1001
#define IDC_GENIEBIOSEDIT               1001
#define IDC_YEDIT                       1002
#define IDC_DISASM                      1003
#define IDC_DISASMLIST                  1003
#define IDC_DISASM_SCROLL               1004
#define IDC_DISASMSCROLL                1004
#define IDC_INES20LIST                  1005
#define IDC_SPEDIT                      1005
#define IDC_UNIFLIST                    1006
#define IDC_PCEDIT                      1006
#define IDC_INESLIST                    1007
#define IDC_INESSTATIC                  1008
#define IDC_INES20STATIC                1009
#define IDC_UNIFSTATIC                  1010
#define IDC_STEPCYCLEBUTTON             1012
#define IDC_STEPBUTTON                  1012
#define IDC_STEPLINEBUTTON              1013
#define IDC_STEPFRAMEBUTTON             1014
#define IDC_RUNBUTTON                   1015
#define IDC_LOGUNHANDLEDIOCHECK         1016
#define IDC_BIOSPATHEDIT                1017
#define IDC_CHEATPATHEDIT               1018
#define IDC_PAUSEAFTERLOADCHECK         1018
#define IDC_SRAMPATHEDIT                1019
#define IDC_EXECUTEBUTTON               1019
#define IDC_PATCHPATHEDIT               1020
#define IDC_COMMANDEDIT                 1020
#define IDC_PALETTEPATHEDIT             1021
#define IDC_NESCHECK                    1021
#define IDC_UNIFCHECK                   1022
#define IDC_UNFCHECK                    1022
#define IDC_FDSCHECK                    1023
#define IDC_NSFCHECK                    1024
#define IDC_CHECK1                      1025
#define IDC_BREAKPOINTLIST              1026
#define IDC_CHECK2                      1027
#define IDC_CHECK3                      1028
#define IDC_CHECK4                      1029
#define IDC_CHECK5                      1030
#define IDC_CHECK6                      1031
#define IDC_BUTTON1                     1032
#define IDC_ADDBPBUTTON                 1032
#define IDC_CARTDBEDITBUTTON            1032
#define IDC_ADDBUTTON                   1032
#define IDC_BROWSEBUTTON                1032
#define IDC_PORT1CONFIGBUTTON           1032
#define IDC_BUTTON2                     1033
#define IDC_EDITBPBUTTON                1033
#define IDC_DELETEBUTTON                1033
#define IDC_PORT2CONFIGBUTTON           1033
#define IDC_BUTTON3                     1034
#define IDC_DELETEBPBUTTON              1034
#define IDC_PORT1CONFIGBUTTON3          1034
#define IDC_EXPCONFIGBUTTON             1034
#define IDC_PIXELSTATIC                 1035
#define IDC_LINESTATIC                  1036
#define IDC_FRAMESTATIC                 1037
#define IDC_RESETRADIO                  1038
#define IDC_NMIRADIO                    1039
#define IDC_IRQRADIO                    1040
#define IDC_WRITERADIO                  1042
#define IDC_WRITECHECK                  1043
#define IDC_READCHECK                   1044
#define IDC_EDIT2                       1045
#define IDC_EDIT3                       1046
#define IDC_STATEPATHEDIT               1047
#define IDC_GENIECHECK                  1048
#define IDC_FDSHLECHECK                 1049
#define IDC_FILTERCOMBO                 1050
#define IDC_FRAMELIMITCHECK             1051
#define IDC_RESOLUTIONCOMBO             1052
#define IDC_SCALECOMBO                  1052
#define IDC_SOUNDENABLEDCHECK           1053
#define IDC_PORT1COMBO                  1054
#define IDC_PORT2COMBO                  1055
#define IDC_EXPANSIONCOMBO              1056
#define IDC_SEARCHLIST                  1057
#define IDC_BEGINBUTTON                 1058
#define IDC_EQUALBUTTON                 1059
#define IDC_NOTEQUALBUTTON              1060
#define IDC_BUTTON4                     1061
#define IDC_BUTTON5                     1062
#define IDC_SOFTRESETBUTTON             1063
#define IDC_HARDRESETBUTTON             1064
#define IDC_SEEKCURRENTPCBUTTON         1065
#define IDC_SEEKADDRESSBUTTON           1066
#define IDC_SEEKADDRESSEDIT             1067
#define IDC_LIST1                       1068
#define IDC_PALETTELIST                 1068
#define IDC_LIST2                       1069
#define IDC_FILELIST                    1069
#define IDC_CARTDBENABLECHECK           1070
#define IDC_CARTDBEDIT                  1071
#define IDC_FILEEDIT                    1072
#define IDC_TITLESTATIC                 1073
#define IDC_URLSTATIC                   1074
#define IDC_COMBO1                      1075
#define IDC_HUESLIDER                   1076
#define IDC_SLIDER2                     1077
#define IDC_SATSLIDER                   1077
#define IDC_HUESATSTATIC                1078
#define IDC_SPIN1                       1079
#define IDC_USEPALETTEFILECHECK         1080
#define IDC_SPIN2                       1081
#define IDC_STARTEDIT                   1081
#define IDC_ENDEDIT                     1082
#define ID_FILE_OPEN                    32771
#define ID_NES_SOFTRESET                32772
#define ID_NES_HARDRESET                32773
#define ID_NES_LOADSTATE                32774
#define ID_NES_SAVESTATE                32775
#define ID_VIEW_DEBUGGER                32776
#define ID_VIEW_MEMORY                  32777
#define ID_VIEW_CONFIGURATION           32778
#define ID_NES_PALETTE                  32779
#define ID_VIEW_PPUDEBUG                32780
#define ID_VIEW_NAMETABLES              32781
#define ID_VIEW_PATTERNTABLES           32782
#define ID_VIEW_SPRITES                 32783
#define ID_VIEW_PALETTE                 32784
#define ID_VIEW_PPU                     32785
#define ID_VIEW_MAPPERCONFIG            32786
#define ID_VIEW_INPUT                   32787
#define ID_CONFIGURATION_GENERAL        32788
#define ID_CONFIGURATION_INPUT          32789
#define ID_CONFIGURATION_MAPPER         32790
#define ID_HELP_SUPPORTEDMAPPERS        32791
#define ID_VIEW_CONSOLE                 32792
#define ID_NES_FDS                      32793
#define ID_FDS_FLIPDISK                 32794
#define ID_VIEW_FULLSCREEN              32797
#define ID_CONFIGURATION_VIDEO          32801
#define ID_NES_PAUSE                    32803
#define ID_VIEW_CHEATS                  32804
#define ID_VIEW_SEARCH                  32805
#define ID_FILE_UNLOAD                  32807
#define ID_FILE_LOADPATCH               32808
#define ID_VIEW_ROMINFORMATION          32811
#define ID_NES_MOVIE                    32812
#define ID_MOVIE_PLAY                   32813
#define ID_MOVIE_RECORD                 32814
#define ID_MOVIE_STOP                   32815
#define ID_RECORD_START                 32816
#define ID_MOVIE_LOAD                   32817
#define ID_MOVIE_SAVE                   32818
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        145
#define _APS_NEXT_COMMAND_VALUE         32819
#define _APS_NEXT_CONTROL_VALUE         1083
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
